image: ghcr.io/itpplasma/devel-tex

variables:
  GIT_HTTPS: "true"

stages:
  - libs
  - codes

fgsl:
  stage: libs
  script:
    - cd libs
    - ../scripts/setup_fgsl.sh
  artifacts:
    paths:
      - libs/fgsl-1.5.0/

mfem:
  stage: libs
  script:
    - cd libs
    - ../scripts/setup_mfem.sh
  artifacts:
    paths:
      - libs/mfem-4.6/

libneo:
  stage: libs
  script:
    - scripts/clone_github.sh libneo
    - cd libneo
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - ./build.sh
  artifacts:
    paths:
      - libneo/

stellopt:
  stage: libs
  rules:  # Run only nightly builds on schedule
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      allow_failure: true
  script:
    - cd libs
    - source ../scripts/setup_stellopt.sh
  artifacts:
    paths:
      - libs/STELLOPT/LIBSTELL/Release/libstell.so
      - libs/STELLOPT/LIBSTELL/Release/libstell.a
      - libs/STELLOPT/VMEC2000/Release/libvmec.a
      - libs/STELLOPT/BOOZ_XFORM/Release/xbooz_xform
      - libs/STELLOPT/COBRAVMEC/Release/xcobravmec
      - libs/STELLOPT/BNORM/Release/xbnorm
      - libs/STELLOPT/WALL_ACCELERATE/Release/xwallacc
      - libs/STELLOPT/VMEC2SPEC/Release/xvmec2spec
      - libs/STELLOPT/J_INVARIANT/Release/xjinvariant
      - libs/STELLOPT/FIELDLINES/Release/xfieldlines
      - libs/STELLOPT/NEO/Release/xneo
      - libs/STELLOPT/VMEC2STEL/Release/xvmec2stel
      - libs/STELLOPT/BOOTSJ/Release/xbootsj
      - libs/STELLOPT/TORLINES/Release/xtorlines
      - libs/STELLOPT/STELLOPTV2/Release/xstelloptv2
      - libs/STELLOPT/MAKEGRID/Release/xgrid
      - libs/STELLOPT/THRIFT/Release/xthrift
      - libs/STELLOPT/VMEC2XGC/Release/xvmec2xgc
      - libs/STELLOPT/PENTA/Release/xpenta
      - libs/STELLOPT/DIAGNO/Release/xdiagno
      - libs/STELLOPT/VMEC2000/Release/xvmec2000
      - libs/STELLOPT/BEAMS3D/Release/xbeams3d
      - libs/STELLOPT/VMEC2PIES/Release/xvmec2pies
      - libs/STELLOPT/VMEC2V690/Release/xvmec2v690
      - libs/STELLOPT/NESCOIL/Release/xnescoil
      - libs/STELLOPT/COILOPT/Release/xcoilopt
      - libs/STELLOPT/DKES/Release/xdkes
      - libs/STELLOPT/BCYCLIC/Release/xbcyclic

test-setup:
  stage: codes
  needs: []
  script:
    - source setup.sh
    - python -c "import libneo"

mephit:
  stage: codes
  needs: ["libneo", "fgsl", "mfem"]
  script:
    - scripts/clone_gitlab.sh MEPHIT
    - cd MEPHIT
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - mkdir build
    - cd build
    - export LIBNEO_DIR=$CI_PROJECT_DIR/libneo/build
    - export MFEM_DIR=$CI_PROJECT_DIR/libs/mfem-4.6/build
    - cmake .. -DFGSL_INC=$CI_PROJECT_DIR/libs/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/libs/fgsl-1.5.0/.libs
    - make -j4
  artifacts:
    paths:
      - MEPHIT/

kim:
  stage: codes
  needs: []
  script:
    - scripts/clone_gitlab.sh kim
    - cd kim
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_Fortran_FLAGS=-I/usr/include/hdf5/serial
    - make
  artifacts:
    paths:
      - kim/

neo2-job:
  stage: codes
  needs: ["libneo", "fgsl"]
  script:
    - source scripts/setup_venv.sh
    - scripts/clone_github.sh NEO-2
    - scripts/setup_neo2.sh
  artifacts:
    paths:
      - NEO-2/

neort:
  stage: codes
  needs: []
  script:
    - mkdir contrib
    - cd contrib
    - ../scripts/clone_github.sh quadpack
    - ../scripts/clone_github.sh vode
    - cd ..
    - scripts/clone_github.sh spline
    - scripts/clone_github.sh BOOZER_MAGFIE
    - scripts/clone_github.sh NEO-RT
    - cd NEO-RT
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - contrib/
      - spline/
      - BOOZER_MAGFIE/
      - NEO-RT/

simple:
  stage: codes
  needs: []
  script:
    - source scripts/setup_venv.sh
    - scripts/clone_github.sh SIMPLE
    - cd SIMPLE
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - ./build.sh
  artifacts:
    paths:
      - SIMPLE/

gorilla:
  stage: codes
  needs: []
  script:
    - scripts/clone_github.sh GORILLA
    - cd GORILLA
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - ./build.sh
  artifacts:
    paths:
      - GORILLA/

efit_to_boozer:
  stage: codes
  needs: []
  script:
    - source scripts/setup_venv.sh
    - scripts/clone_github.sh efit_to_boozer
    - cd efit_to_boozer
    - make
  artifacts:
    paths:
      - efit_to_boozer/

chease:
  stage: codes
  needs: []
  script:
    - scripts/setup_chease.sh
  artifacts:
    paths:
      - CHEASE/
