image: ghcr.io/itpplasma/devel-tex

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" &&      $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

variables:
  GIT_HTTPS: "true"

stages:
  - external
  - codes
  - projects


### External Libs and Codes

fgsl:
  stage: external
  script:
    - cd external
    - ../scripts/setup_fgsl.sh
    - export PACKAGENAME=fgsl
    - export VERSION=1.5.0
    - tar czf ${PACKAGENAME}-${VERSION}.tar.gz ${PACKAGENAME}-${VERSION}
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${PACKAGENAME}-${VERSION}.tar.gz ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGENAME}/${VERSION}/${PACKAGENAME}-${VERSION}.tar.gz'
  artifacts:
    paths:
      - external/fgsl-1.5.0/

mfem:
  stage: external
  script:
    - cd external
    - ../scripts/setup_mfem.sh
  artifacts:
    paths:
      - external/mfem-4.6.2-rc0/

libneo:
  stage: external
  script:
    - source scripts/util.sh
    - source scripts/setup_venv.sh
    - source scripts/setup_libneo.sh
  artifacts:
    paths:
      - libneo/
      - efit_to_boozer/

stellopt:
  stage: external
  rules:  # Run only nightly builds on schedule
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      allow_failure: true
  script:
    - cd external
    - source ../scripts/setup_stellopt.sh
  artifacts:
    paths:
      - external/STELLOPT/LIBSTELL/Release/libstell.so
      - external/STELLOPT/LIBSTELL/Release/libstell.a
      - external/STELLOPT/VMEC2000/Release/libvmec.a
      - external/STELLOPT/BOOZ_XFORM/Release/xbooz_xform
      - external/STELLOPT/COBRAVMEC/Release/xcobravmec
      - external/STELLOPT/BNORM/Release/xbnorm
      - external/STELLOPT/WALL_ACCELERATE/Release/xwallacc
      - external/STELLOPT/VMEC2SPEC/Release/xvmec2spec
      - external/STELLOPT/J_INVARIANT/Release/xjinvariant
      - external/STELLOPT/FIELDLINES/Release/xfieldlines
      - external/STELLOPT/NEO/Release/xneo
      - external/STELLOPT/VMEC2STEL/Release/xvmec2stel
      - external/STELLOPT/BOOTSJ/Release/xbootsj
      - external/STELLOPT/TORLINES/Release/xtorlines
      - external/STELLOPT/STELLOPTV2/Release/xstelloptv2
      - external/STELLOPT/MAKEGRID/Release/xgrid
      - external/STELLOPT/THRIFT/Release/xthrift
      - external/STELLOPT/VMEC2XGC/Release/xvmec2xgc
      - external/STELLOPT/PENTA/Release/xpenta
      - external/STELLOPT/DIAGNO/Release/xdiagno
      - external/STELLOPT/VMEC2000/Release/xvmec2000
      - external/STELLOPT/BEAMS3D/Release/xbeams3d
      - external/STELLOPT/VMEC2PIES/Release/xvmec2pies
      - external/STELLOPT/VMEC2V690/Release/xvmec2v690
      - external/STELLOPT/NESCOIL/Release/xnescoil
      - external/STELLOPT/COILOPT/Release/xcoilopt
      - external/STELLOPT/DKES/Release/xdkes
      - external/STELLOPT/BCYCLIC/Release/xbcyclic

chease:
  stage: external
  script:
    - cd external
    - ../scripts/setup_chease.sh
  artifacts:
    paths:
      - external/CHEASE/


### Codes

test-setup:
  stage: codes
  needs: []
  script:
    - source setup.sh
    - source activate.sh
    - python -c "import libneo"

mephit:
  stage: codes
  needs: ["libneo", "mfem"]
  script:
    - pushd external
    - export PACKAGENAME=fgsl
    - export VERSION=1.5.0
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -L ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGENAME}/${VERSION}/${PACKAGENAME}.${VERSION}.tar.gz -o - | tar -xz'
    - popd
    - source scripts/util.sh
    - clone_gitlab MEPHIT
    - source scripts/setup_mephit.sh
  artifacts:
    paths:
      - MEPHIT/

kim:
  stage: codes
  needs: []
  script:
    - source scripts/util.sh
    - clone_gitlab kim
    - cd kim
    - ../scripts/checkout_branch.sh $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_Fortran_FLAGS=-I/usr/include/hdf5/serial
    - make
  artifacts:
    paths:
      - kim/

neo2-job:
  stage: codes
  needs: ["fgsl"]
  script:
    - source scripts/setup_venv.sh
    - source activate.sh
    - source scripts/setup_libneo.sh
    - clone_github NEO-2
    - scripts/setup_neo2.sh
  artifacts:
    paths:
      - NEO-2/

neort:
  stage: codes
  needs: []
  script:
    - source scripts/util.sh
    - mkdir contrib
    - cd contrib
    - clone_github quadpack
    - clone_github vode
    - cd ..
    - clone_github spline
    - clone_github BOOZER_MAGFIE
    - clone_github NEO-RT
    - cd NEO-RT
    - ../scripts/checkout_branch.sh $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - contrib/
      - spline/
      - BOOZER_MAGFIE/
      - NEO-RT/

simple:
  stage: codes
  needs: []
  script:
    - source scripts/util.sh
    - source scripts/setup_venv.sh
    - clone_github SIMPLE
    - cd SIMPLE
    - ../scripts/checkout_branch.sh $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - ./build.sh
  artifacts:
    paths:
      - SIMPLE/

gorilla:
  stage: codes
  needs: []
  script:
    - source scripts/util.sh
    - clone_github GORILLA
    - cd GORILLA
    - ../scripts/checkout_branch.sh $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - ./build.sh
  artifacts:
    paths:
      - GORILLA/


### Projects

ntv-demo:
  stage: projects
  needs: ["libneo"]
  script:
    - source scripts/util.sh
    - clone_github ntv-demo
    - cd ntv-demo
  artifacts:
    paths:
      - ntv-demo/
