image: ghcr.io/itpplasma/devel-tex

stages:
  - libs
  - codes

libneo:
  stage: libs
  script:
    - pwd
    - git clone https://github.com/itpplasma/libneo
    - cd libneo
    - ../checkout_branch.sh
    - ./build.sh
  artifacts:
    paths:
      - libneo/

fgsl:
  stage: libs
  script:
    - wget https://doku.lrz.de/files/10746505/10746508/1/1684600947173/fgsl-1.5.0.tar.gz
    - tar xzvf fgsl-1.5.0.tar.gz
    - cd fgsl-1.5.0
    - ./configure
    - make
    - find . -name "*.so"
    - find . -name "*.a"
    - pwd
  artifacts:
    paths:
      - fgsl-1.5.0/

mephit-job:
  stage: codes
  script:
    - git clone https://user:$READ_TOKEN@gitlab.tugraz.at/plasma/codes/MEPHIT.git
    - cd MEPHIT
    - mkdir build && cd build
    - cmake ..
    - make
    # TODO: Install MFEM in Docker image
    # TODO: Test
  allow_failure: true

kim-job:
  allow_failure: true
  stage: codes
  script:
    - git clone https://user:$READ_TOKEN@gitlab.tugraz.at/plasma/codes/kim.git
    - cd kim
    - mkdir build && cd build
    - cmake ..
    - make
    # TODO: Fix preprocessor error
    # TODO: Test
  allow_failure: true

neo2-job:
  stage: codes
  script:
    - git clone https://oauth2:$GITHUB_TOKEN@github.com/itpplasma/NEO-2
    # Build NEO-2-PAR
    - cd NEO-2/NEO-2-PAR/Build-Debug
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libneo/build -DFGSL_INC=$CI_PROJECT_DIR/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/fgsl-1.5.0/.libs
    - make
    # TODO: Test NEO-2-PAR
    # Build NEO-2-QL
    - cd ../../NEO-2-QL
    - mkdir Build
    - cd Build
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libneo/build -DFGSL_INC=$CI_PROJECT_DIR/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/fgsl-1.5.0/.libs
    - make
    # TODO: Test NEO-2-QL

neort-job:
  stage: codes
  script:
    - mkdir contrib
    - cd contrib
    - git clone https://github.com/itpplasma/quadpack
    - git clone https://github.com/itpplasma/vode
    - cd ..
    - git clone https://github.com/itpplasma/spline
    - git clone https://github.com/itpplasma/BOOZER_MAGFIE
    - git clone https://github.com/itpplasma/NEO-RT
    - cd NEO-RT
    - mkdir build && cd build
    - cmake ..
    - make
    # TODO: Test

simple-job:
  stage: codes
  script:
    - git clone https://github.com/itpplasma/SIMPLE
    - cd SIMPLE
    - ./build.sh
    # TODO: Test

gorilla-job:
  stage: codes
  script:
    - git clone https://github.com/itpplasma/GORILLA
    - cd GORILLA
    - ./build.sh
    # TODO: Test
