image: ghcr.io/itpplasma/devel-tex

variables:
  GIT_HTTPS: "true"

stages:
  - libs
  - codes

test-setup:
  stage: libs
  script:
    - ./setup.sh
    - source activate.sh
    - python -c "import libneo"

libneo:
  stage: libs
  script:
    - pwd
    - scripts/clone_github.sh libneo
    - cd libneo
    - ../scripts/checkout_branch.sh ${branch}
    - ./build.sh
  artifacts:
    paths:
      - libneo/

fgsl:
  stage: libs
  script:
    - wget https://doku.lrz.de/files/10746505/10746508/1/1684600947173/fgsl-1.5.0.tar.gz
    - tar xzvf fgsl-1.5.0.tar.gz
    - cd fgsl-1.5.0
    - ./configure
    - make
    - find . -name "*.so"
    - find . -name "*.a"
    - pwd
  artifacts:
    paths:
      - fgsl-1.5.0/

mephit-job:
  stage: codes
  script:
    - scripts/clone_gitlab.sh MEPHIT
    - cd MEPHIT
    - ./build.sh
    # TODO: Install MFEM in Docker image
    # TODO: Test
  allow_failure: true

kim-job:
  allow_failure: true
  stage: codes
  script:
    - scripts/clone_gitlab.sh kim
    - cd kim
    - ./build.sh
    # TODO: Fix preprocessor error
    # TODO: Test
  allow_failure: true

neo2-job:
  stage: codes
  script:
    - scripts/clone_github.sh NEO-2
    # Build NEO-2-PAR
    - cd NEO-2/NEO-2-PAR/Build-Debug
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libneo/build -DFGSL_INC=$CI_PROJECT_DIR/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/fgsl-1.5.0/.libs
    - make
    # TODO: Test NEO-2-PAR
    # Build NEO-2-QL
    - cd ../../NEO-2-QL
    - mkdir Build
    - cd Build
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libneo/build -DFGSL_INC=$CI_PROJECT_DIR/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/fgsl-1.5.0/.libs
    - make
    # TODO: Test NEO-2-QL

neort-job:
  stage: codes
  script:
    - mkdir contrib
    - cd contrib
    - ../scripts/clone_github.sh quadpack
    - ../scripts/clone_github.sh vode
    - cd ..
    - scripts/clone_github.sh spline
    - scripts/clone_github.sh BOOZER_MAGFIE
    - scripts/clone_github.sh NEO-RT
    - cd NEO-RT
    - mkdir build && cd build
    - cmake ..
    - make
    # TODO: Test

simple-job:
  stage: codes
  script:
    - scripts/clone_github.sh SIMPLE
    - cd SIMPLE
    - ./build.sh
    # TODO: Test

gorilla-job:
  stage: codes
  script:
    - scripts/clone_github.sh GORILLA
    - cd GORILLA
    - ./build.sh
    # TODO: Test
