image: ghcr.io/itpplasma/devel-tex

variables:
  GIT_HTTPS: "true"

stages:
  - libs
  - codes

fgsl:
  stage: libs
  script:
    - cd libs
    - ../scripts/setup_fgsl.sh
  artifacts:
    paths:
      - libs/fgsl-1.5.0/

mfem:
  stage: libs
  script:
    - cd libs
    - ../scripts/setup_mfem.sh
  artifacts:
    paths:
      - libs/mfem-4.6/

libneo:
  stage: libs
  script:
    - cd libs
    - ../scripts/clone_github.sh libneo
    - cd libneo
    - ../../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - ./build.sh
  artifacts:
    paths:
      - libs/libneo/

omfit:
  stage: libs
  script:
    - scripts/setup_venv.sh
    - source activate.sh
    - cd libs
    - ../scripts/setup_omfit.sh
  artifacts:
    paths:
      - libs/OMFIT/

stellopt:
  stage: libs
  script:
    - cd libs
    - source ../scripts/setup_stellopt.sh
  artifacts:
    paths:
      - libs/STELLOPT/

test-setup:
  stage: codes
  script:
    - ./setup.sh
    - source activate.sh
    - python -c "import libneo"
  dependencies: []

mephit-job:
  stage: codes
  script:
    - scripts/clone_gitlab.sh MEPHIT
    - cd MEPHIT
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - mkdir build
    - cd build
    - export LIBNEO_DIR=$CI_PROJECT_DIR/libs/libneo/build
    - export MFEM_DIR=$CI_PROJECT_DIR/libs/mfem-4.6/build
    - cmake .. -DFGSL_INC=$CI_PROJECT_DIR/libs/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/libs/fgsl-1.5.0/.libs
    - make -j4
  artifacts:
    paths:
      - MEPHIT/

kim-job:
  stage: codes
  script:
    - scripts/clone_gitlab.sh kim
    - cd kim
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_Fortran_FLAGS=-I/usr/include/hdf5/serial
    - make
  artifacts:
    paths:
      - kim/

neo2-job:
  stage: codes
  script:
    - scripts/clone_github.sh NEO-2
    - cd NEO-2
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    # Build NEO-2-PAR
    - cd NEO-2-PAR/Build-Debug
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libs/libneo/build -DFGSL_INC=$CI_PROJECT_DIR/libs/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/libs/fgsl-1.5.0/.libs
    - make
    # Build NEO-2-QL
    - cd ../../NEO-2-QL
    - mkdir Build
    - cd Build
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libs/libneo/build -DFGSL_INC=$CI_PROJECT_DIR/libs/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/libs/fgsl-1.5.0/.libs
    - make
  artifacts:
    paths:
      - NEO-2/

neort-job:
  stage: codes
  script:
    - mkdir contrib
    - cd contrib
    - ../scripts/clone_github.sh quadpack
    - ../scripts/clone_github.sh vode
    - cd ..
    - scripts/clone_github.sh spline
    - scripts/clone_github.sh BOOZER_MAGFIE
    - scripts/clone_github.sh NEO-RT
    - cd NEO-RT
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - contrib/
      - spline/
      - BOOZER_MAGFIE/
      - NEO-RT/

simple-job:
  stage: codes
  script:
    - scripts/setup_venv.sh
    - source activate.sh
    - scripts/clone_github.sh SIMPLE
    - cd SIMPLE
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - ./build.sh
  artifacts:
    paths:
      - SIMPLE/

gorilla-job:
  stage: codes
  script:
    - scripts/clone_github.sh GORILLA
    - cd GORILLA
    - ../scripts/checkout_branch.sh $CI_COMMIT_BRANCH
    - ./build.sh
  artifacts:
    paths:
      - GORILLA/

efit_to_boozer-job:
  stage: codes
  script:
    - scripts/setup_venv.sh
    - source activate.sh
    - scripts/clone_gitlab.sh efit_to_boozer
    - cd efit_to_boozer
    - make
    - cd python
    - make
  artifacts:
    paths:
      - efit_to_boozer/

chease:
  stage: codes
  script:
    - scripts/setup_chease.sh
  artifacts:
    paths:
      - CHEASE/
