image: ghcr.io/itpplasma/devel-tex

stages:
  - libs
  - codes

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

  - eval $(ssh-agent -s)

  - echo "$NEO2_DEPLOY_KEY" | tr -d '\r' | ssh-add -

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - ssh-keyscan github.com >> ~/.ssh/known_hosts

libneo:
  stage: libs
  script:
    - pwd
    - git clone https://github.com/itpplasma/libneo
    - cd libneo
    - ../checkout_branch.sh
    - ./build.sh
  artifacts:
    paths:
      - libneo/

fgsl:
  stage: libs
  script:
    - wget https://doku.lrz.de/files/10746505/10746508/1/1684600947173/fgsl-1.5.0.tar.gz
    - tar xzvf fgsl-1.5.0.tar.gz
    - cd fgsl-1.5.0
    - ./configure && make
  artifacts:
    paths:
      - fgsl-1.5.0/

mephit-job:
  stage: codes
  script:
    - git clone https://user:$READ_TOKEN@gitlab.tugraz.at/plasma/codes/MEPHIT.git
    # TODO: Build and test

kim-job:
  stage: codes
  script:
    - git clone https://user:$READ_TOKEN@gitlab.tugraz.at/plasma/codes/kim.git
    # TODO: Build and test

neo2-job:
  stage: codes
  script:
    - git clone git@github.com:itpplasma/NEO-2
    # Build NEO-2-PAR
    - cd NEO-2/NEO-2-PAR/Build-Debug
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libneo/build -DFGSL_LIB=$HOME/fgsl-1.5.0/.libs
    - make
    # TODO: Test NEO-2-PAR
    # Build NEO-2-QL
    - cd ../../NEO-2-QL
    - mkdir Build
    - cd Build
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libneo/build -DFGSL_LIB=$HOME/fgsl-1.5.0/.libs
    - make
    # TODO: Test NEO-2-QL

neort-job:
  stage: codes
  script:
    - mkdir contrib
    - cd contrib
    - git clone https://github.com/itpplasma/quadpack
    - git clone https://github.com/itpplasma/vode
    - cd ..
    - git clone https://github.com/itpplasma/spline
    - git clone https://github.com/itpplasma/BOOZER_MAGFIE
    - git clone https://github.com/itpplasma/NEO-RT
    # TODO: Build and test

simple-job:
  stage: codes
  script:
    - git clone https://github.com/itpplasma/SIMPLE
    # TODO: Build and test

gorilla-job:
  stage: codes
  script:
    - git clone https://github.com/itpplasma/GORILLA
    # TODO: Build and test
