image: ghcr.io/itpplasma/devel-tex

stages:
  - libneo
  - codes

libneo-job:
  stage: libneo
  script:
    - git clone https://github.com/itpplasma/libneo
  artifacts:
    paths:
      - libneo/

mephit-job:
  stage: codes
  script:
    - git clone https://user:$READ_TOKEN@gitlab.tugraz.at/plasma/codes/MEPHIT.git

kim-job:
  stage: codes
  script:
    - git clone https://user:$READ_TOKEN@gitlab.tugraz.at/plasma/codes/kim.git

neo2-job:
  stage: codes
  script:
    - git clone https://github.com/itpplasma/NEO-2

neort-job:
  stage: codes
  script:
    - mkdir contrib
    - cd contrib
    - git clone git@github.com:itpplasma/quadpack
    - git clone git@github.com:itpplasma/vode
    - cd ..
    - git clone git@github.com:itpplasma/spline
    - git clone git@github.com:itpplasma/BOOZER_MAGFIE
    - git clone git@github.com:itpplasma/NEO-RT

simple-job:
  stage: codes
  script:
    - git clone https://github.com/itpplasma/SIMPLE

gorilla-job:
  stage: codes
  script:
    - git clone https://github.com/itpplasma/GORILLA
