image: ghcr.io/itpplasma/devel-tex

variables:
  GIT_HTTPS: "true"

stages:
  - libs
  - codes

fgsl:
  stage: libs
  script:
    - cd libs
    - ../scripts/setup_fgsl.sh
  artifacts:
    paths:
      - libs/fgsl-1.5.0/

mfem:
  stage: libs
  script:
    - cd libs
    - ../scripts/setup_mfem.sh
  artifacts:
    paths:
      - libs/mfem-4.6/

libneo:
  stage: libs
  script:
    - cd libs
    - ../scripts/clone_github.sh libneo
    - cd libneo
    - ../../scripts/checkout_branch.sh ${branch}
    - ./build.sh
  artifacts:
    paths:
      - libs/libneo/

test-setup:
  stage: codes
  script:
    - ./setup.sh
    - source activate.sh
    - python -c "import libneo"
  dependencies: []

mephit-job:
  stage: codes
  script:
    - scripts/clone_gitlab.sh MEPHIT
    - cd MEPHIT
    - ../scripts/checkout_branch.sh ${branch}
    - mkdir build
    - cd build
    - export LIBNEO_DIR=$CI_PROJECT_DIR/libs/libneo/build
    - export MFEM_DIR=$CI_PROJECT_DIR/libs/mfem-4.6/build
    - cmake .. -DFGSL_INC=$CI_PROJECT_DIR/libs/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/libs/fgsl-1.5.0/.libs
    - make -j4
    # TODO: Test
  allow_failure: true

kim-job:
  stage: codes
  script:
    - scripts/clone_gitlab.sh kim
    - cd kim
    - ../scripts/checkout_branch.sh ${branch}
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_Fortran_FLAGS=-I/usr/include/hdf5/serial
    - make
    # TODO: Test

neo2-job:
  stage: codes
  script:
    - scripts/clone_github.sh NEO-2
    # Build NEO-2-PAR
    - cd NEO-2/NEO-2-PAR/Build-Debug
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libs/libneo/build -DFGSL_INC=$CI_PROJECT_DIR/libs/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/libs/fgsl-1.5.0/.libs
    - make
    # TODO: Test NEO-2-PAR
    # Build NEO-2-QL
    - cd ../../NEO-2-QL
    - mkdir Build
    - cd Build
    - cmake .. -DNEO2_Libs=$CI_PROJECT_DIR/libs/libneo/build -DFGSL_INC=$CI_PROJECT_DIR/libs/fgsl-1.5.0 -DFGSL_LIB=$CI_PROJECT_DIR/libs/fgsl-1.5.0/.libs
    - make
    # TODO: Test NEO-2-QL

neort-job:
  stage: codes
  script:
    - mkdir contrib
    - cd contrib
    - ../scripts/clone_github.sh quadpack
    - ../scripts/clone_github.sh vode
    - cd ..
    - scripts/clone_github.sh spline
    - scripts/clone_github.sh BOOZER_MAGFIE
    - scripts/clone_github.sh NEO-RT
    - cd NEO-RT
    - ../scripts/checkout_branch.sh ${branch}
    - mkdir build && cd build
    - cmake ..
    - make
    # TODO: Test

simple-job:
  stage: codes
  script:
    - scripts/clone_github.sh SIMPLE
    - cd SIMPLE
    - ../scripts/checkout_branch.sh ${branch}
    - ./build.sh
    # TODO: Test

gorilla-job:
  stage: codes
  script:
    - scripts/clone_github.sh GORILLA
    - cd GORILLA
    - ../scripts/checkout_branch.sh ${branch}
    - ./build.sh
    # TODO: Test
