#!/usr/bin/env bash

apt-get install -y -q --no-install-recommends \
    file \
    sudo \
    environment-modules \
    unzip \
    apt-transport-https \
    build-essential \
    ca-certificates \
    curl \
    libssl-dev \
    locales \
    openssh-client \
    rsync \
    wget \
    git \
    git-lfs \
    git-annex \
    gpg \
    gfortran \
    ninja-build \
    cmake \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    python-dev-is-python3 \
    python3-numpy \
    python3-scipy \
    python3-matplotlib \
    python3-pytest \
    nix-bin \
    bash \
    csh \
    time \
    ed \
    gcovr \
    lcov
