#!/usr/bin/env bash
# Render/check/install the explicit Squid gateway for strict AI egress mode.
# This never installs packages or starts a service implicitly.
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd -- "${SCRIPT_DIR}/../.." && pwd)
SOURCE_DIR=${AI_EGRESS_CONFIG_DIR:-${ROOT_DIR}/config/ai-egress}
INSTALL_DIR=${AI_EGRESS_PROXY_CONFIG_DIR:-/etc/ai-egress}
DOMAIN_FILE=${AI_EGRESS_DOMAIN_FILE:-${SOURCE_DIR}/deny-domains.txt}
NETWORK_FILE=${AI_EGRESS_NETWORK_FILE:-${SOURCE_DIR}/deny-networks.txt}
BRIDGE=${AI_EGRESS_BRIDGE:-incusbr0}
SUBNET=${AI_EGRESS_SUBNET:-10.234.0.0/24}
LISTEN_IP=${AI_EGRESS_DNS_IP:-10.234.0.1}
PORT=${AI_EGRESS_PROXY_PORT:-3128}
ACTION=check

usage() {
    cat <<'EOF'
Usage: ai-egress-proxy.sh [--check|--dry-run|--apply]

--check    verify prerequisites and policy inputs (default)
--dry-run  render squid.conf and the systemd unit without changing the host
--apply    install config/unit after validation; does not enable or start it

The Debian/Ubuntu package `squid` is a prerequisite. This script deliberately
does not apt-install it, and --apply refuses to proceed when it is absent.
After review, start explicitly with:
  sudo systemctl enable --now ai-egress-proxy.service
The nftables script must separately be run in strict proxy mode.
EOF
}

die() { echo "ai-egress-proxy: $*" >&2; exit 1; }

while (($#)); do
    case "$1" in
        --check) ACTION=check ;;
        --dry-run) ACTION=dry-run ;;
        --apply) ACTION=apply ;;
        -h|--help) usage; exit 0 ;;
        *) die "unknown option: $1" ;;
    esac
    shift
done

[[ -r ${DOMAIN_FILE} ]] || die "domain list is not readable: ${DOMAIN_FILE}"
[[ -r ${NETWORK_FILE} ]] || die "network list is not readable: ${NETWORK_FILE}"
[[ ${SUBNET} == */* && ${LISTEN_IP} != */* ]] || die "invalid subnet/listen address"
[[ ${PORT} =~ ^[0-9]+$ && ${PORT} -ge 1 && ${PORT} -le 65535 ]] || die "invalid proxy port"

find_squid() {
    command -v squid 2>/dev/null || command -v squid4 2>/dev/null || true
}

SQUID_BIN=${AI_EGRESS_SQUID_BIN:-$(find_squid)}
if [[ ${ACTION} == check || ${ACTION} == apply ]] && [[ -z ${SQUID_BIN} ]]; then
    die "Squid is not installed; install the official squid package, then rerun"
fi

read_values() {
    local file=$1 line
    while IFS= read -r line || [[ -n ${line} ]]; do
        line=${line%%#*}
        line=${line//[[:space:]]/}
        [[ -n ${line} ]] && printf '%s\n' "${line}"
    done < "${file}"
}

mapfile -t NETWORKS < <(read_values "${NETWORK_FILE}")
mapfile -t DOMAINS < <(read_values "${DOMAIN_FILE}")
((${#NETWORKS[@]})) || die "network list is empty"
((${#DOMAINS[@]})) || die "domain list is empty"

mapfile -t DENIED_IPS < <(
    if [[ ${AI_EGRESS_RESOLVE:-1} == 1 ]]; then
        for domain in "${DOMAINS[@]}"; do
            getent ahostsv4 "${domain}" 2>/dev/null ||
                echo "unresolved:${domain}" >&2
        done | awk '$1 ~ /^[0-9]+(\.[0-9]+){3}$/ {print $1}' | sort -u
    fi
)

render_config() {
    cat <<EOF
# Generated by ${SCRIPT_DIR}/ai-egress-proxy.sh. Do not edit.
http_port ${LISTEN_IP}:${PORT}
visible_hostname ai-egress-proxy
cache_effective_user proxy
cache_effective_group proxy
cache deny all
cache_mem 0 MB
maximum_object_size 0 KB
forwarded_for delete
via off

acl ai_clients src ${SUBNET}
acl ai_denied_domains dstdomain "${INSTALL_DIR}/deny-domains.txt"
acl ai_denied_networks dst "${INSTALL_DIR}/deny-networks.txt"
acl ai_numeric_ip dstdom_regex -i ^[0-9]+(\.[0-9]+){3}$
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

# Deny is evaluated before the sole client allow. There is no open proxy.
http_access deny !ai_clients
http_access deny !Safe_ports
http_access deny ai_denied_domains
http_access deny ai_numeric_ip
http_access deny ai_denied_networks
http_access deny CONNECT !SSL_ports
http_access allow ai_clients
http_access deny all

access_log stdio:/var/log/squid/ai-egress-access.log
cache_log /var/log/squid/ai-egress-cache.log
pid_filename /run/squid/ai-egress.pid
EOF
}

render_unit() {
    cat <<EOF
[Unit]
Description=Strict egress proxy for AI Incus containers
After=network-online.target incus.service
Wants=network-online.target
ConditionPathExists=${INSTALL_DIR}/squid.conf

[Service]
Type=simple
ExecStart=${SQUID_BIN:-/usr/sbin/squid} -N -f ${INSTALL_DIR}/squid.conf
Restart=on-failure
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=strict
RuntimeDirectory=squid
ReadWritePaths=/run/squid /var/log/squid

[Install]
WantedBy=multi-user.target
EOF
}

case ${ACTION} in
    check)
        command -v getent >/dev/null || die "getent is required"
        [[ -x ${SQUID_BIN} ]] || die "Squid is not executable: ${SQUID_BIN}"
        if command -v ip >/dev/null && ! ip -4 addr show dev "${BRIDGE}" | grep -Fq " ${LISTEN_IP}/"; then
            echo "warning: ${LISTEN_IP} is not currently configured on ${BRIDGE}" >&2
        fi
        echo "configuration OK (Squid ${SQUID_BIN}; ${LISTEN_IP}:${PORT}; clients ${SUBNET})"
        ;;
    dry-run)
        echo '# --- squid.conf ---'
        render_config
        echo '# --- systemd/ai-egress-proxy.service ---'
        render_unit
        ;;
    apply)
        [[ ${EUID} -eq 0 ]] || die "--apply must run as root"
        command -v install >/dev/null || die "install is required"
        tmp=$(mktemp)
        trap 'rm -f "${tmp}"' EXIT
        render_config > "${tmp}"
        install -d -m 0755 "${INSTALL_DIR}"
        # Squid drops privileges before opening its access/cache logs.  The
        # official package may create this directory as root, so make the
        # explicitly scoped log directory writable by the proxy account.
        install -d -o proxy -g proxy -m 0750 /var/log/squid
        install -m 0644 "${DOMAIN_FILE}" "${INSTALL_DIR}/deny-domains.txt"
        install -m 0644 "${NETWORK_FILE}" "${INSTALL_DIR}/deny-networks.txt"
        printf '%s\n' "${DENIED_IPS[@]}" > "${tmp}.ips"
        install -m 0644 "${tmp}.ips" "${INSTALL_DIR}/deny-service-ips.txt"
        install -m 0644 "${tmp}" "${INSTALL_DIR}/squid.conf"
        "${SQUID_BIN}" -k parse -f "${INSTALL_DIR}/squid.conf"
        render_unit | install -m 0644 /dev/stdin /etc/systemd/system/ai-egress-proxy.service
        systemctl daemon-reload
        echo "installed ${INSTALL_DIR}/squid.conf and ai-egress-proxy.service"
        echo "not started; review, then: sudo systemctl enable --now ai-egress-proxy.service"
        ;;
esac
