# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_HTTPS: "true"
  CODE_BRANCH: "${{ github.head_ref }}"

jobs:
  code:
    name: Build and test
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y && sudo apt-get install -y -q --no-install-recommends \
            apt-transport-https \
            build-essential \
            ca-certificates \
            curl \
            libssl-dev \
            openssh-client \
            rsync \
            wget \
            git \
            gfortran \
            ninja-build \
            cmake \
            python3 \
            python3-dev \
            python3-pip \
            python3-venv

          sudo apt-get install -y -q --no-install-recommends \
            python3-tk \
            idle3 \
            findent \
            expect \
            environment-modules

          sudo apt-get install -y -q --no-install-recommends \
            pkg-config \
            libsuitesparse-dev \
            libopenblas-dev \
            libsuperlu-dev \
            libhdf5-dev \
            libhdf5-openmpi-dev \
            libnetcdf-dev \
            libnetcdff-dev \
            libfftw3-dev \
            libgsl-dev \
            libopenmpi-dev \
            libscalapack-openmpi-dev \
            libpcre3-dev \
            libreadline-dev \
            h5utils \
            hdf5-tools \
            netcdf-bin \
            libmetis-dev \
            libboost-all-dev

      - name: Download Release  # TODO: make this dynamic
        run: |
          wget https://github.com/itpplasma/code/releases/download/v2025.01.02/code-v2025.01.02.tar.gz -O /tmp/code.tar.gz

      - name: Extract tarball
        run: |
          tar -xzvf /tmp/code.tar.gz

      - name: NEO-2
        run: |
          source activate.sh
          clone_github NEO-2
          pushd NEO-2
            make
          popd

      - name: NEO-RT
        run: |
          source activate.sh
          clone_github NEO-RT
          source scripts/setup/neort.sh

      - name: SIMPLE
        run: |
          source activate.sh
          clone_github SIMPLE
          pushd SIMPLE
            make
          popd

      - name: GORILLA
        run: |
          source activate.sh
          clone_github GORILLA
          pushd GORILLA
            ./build.sh
          popd

      - name: MEPHIT
        run: |
          source activate.sh
          clone_github MEPHIT
          source /etc/profile.d/modules.sh
          module use -a $CODE/modules
          module load mephit
          cd MEPHIT
          $CODE/scripts/checkout_branch.sh $CODE_BRANCH
          make
          pip install -e .
