name: CI

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Docker Image
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: docker-image-${{ github.sha }}
          restore-keys: |
            docker-image-

      - name: Load Docker Image from Cache
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "Cache hit, loading image..."
          docker load < /tmp/docker-cache/my-image.tar

      - name: Pull Docker Image if Cache Miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss, pulling image..."
          docker pull ghcr.io/itpplasma/devel-tex:latest
          mkdir -p /tmp/docker-cache
          docker save ghcr.io/itpplasma/devel-tex:latest > /tmp/docker-cache/my-image.tar

  ci-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/itpplasma/devel-tex:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run CI/CD Steps
        run: |
          # Your CI/CD steps
          echo "Running tests inside the cached Docker container"
