# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_HTTPS: "true"

jobs:
  MEPHIT:
    name: Build and test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/itpplasma/devel-tex:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          source scripts/setup.sh

      - name: NEO-2
        run: |
          source activate.sh
          clone_github NEO-2
          source scripts/setup/neo2.sh

      - name: NEO-RT
        run: |
          source activate.sh
          clone_github NEO-RT
          source scripts/setup/neort.sh

      - name: SIMPLE
        run: |
          source activate.sh
          clone_github SIMPLE
          pushd SIMPLE
            make
          popd

      - name: GORILLA
        run: |
          source activate.sh
          clone_github GORILLA
          pushd GORILLA
            ./build.sh
          popd

      - name: MEPHIT
        run: |
          source activate.sh
          pushd external
            ../scripts/setup/mfem.sh
          popd
          clone_github MEPHIT
          source scripts/setup/mephit.sh

      - name: Checkout KAMEL
        uses: actions/checkout@v3
        with:
          repository: itpplasma/KAMEL
          path: KAMEL
          token: ${{ secrets.READ_TOKEN }}

      - name: Build KAMEL
        run: |
          source activate.sh
          source scripts/setup/kamel.sh
