name: Mirror Repository

on:
  push:
    branches:
      - "*"

jobs:
  push-to-mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Push to remote mirror
      env:
        GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      run: |
        git remote add gitlab https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.tugraz.at/plasma/code.git
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        git pull --ff-only gitlab $CURRENT_BRANCH || true
        git push gitlab $CURRENT_BRANCH:$CURRENT_BRANCH
