name: SETUP

on:
  workflow_dispatch:

env:
  GIT_HTTPS: "true"

jobs:
  MEPHIT:
    name: Build and test
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y && sudo apt-get install -y -q --no-install-recommends \
            apt-transport-https \
            build-essential \
            ca-certificates \
            curl \
            libssl-dev \
            openssh-client \
            rsync \
            wget \
            git \
            gfortran \
            ninja-build \
            cmake \
            python3 \
            python3-dev \
            python3-pip \
            python3-venv

          sudo apt-get install -y -q --no-install-recommends \
            procps \
            nano \
            vim \
            htop \
            ncdu \
            less \
            gdb \
            cmake-curses-gui \
            valgrind \
            dbus-x11 \
            kcachegrind \
            python3-tk \
            idle3 \
            findent \
            expect \
            environment-modules

          sudo apt-get install -y -q --no-install-recommends \
            pkg-config \
            libsuitesparse-dev \
            libopenblas-dev \
            libsuperlu-dev \
            libhdf5-dev \
            libhdf5-openmpi-dev \
            libnetcdf-dev \
            libnetcdff-dev \
            libfftw3-dev \
            libgsl-dev \
            libopenmpi-dev \
            libscalapack-openmpi-dev \
            libpcre3-dev \
            libreadline-dev \
            h5utils \
            hdf5-tools \
            netcdf-bin \
            libmetis-dev \
            libboost-all-dev \
            libtriangle-dev

      - name: Setup
        run: |
          source scripts/setup.sh
          pushd external
            ../scripts/setup/mfem.sh
          popd

      - name: Build tarball
        run: |
          tar -czf /tmp/code.tar.gz .

      - name: Upload tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: /tmp/code.tar.gz
